import { projectId, publicAnonKey } from "../../utils/supabase/info";

/**
 * Centralized env access so the app works both:
 * - locally without any .env configured (falls back to the autogenerated Supabase info)
 * - in production with Vercel env vars (recommended)
 */

export const supabaseUrl =
  import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;

export const supabaseAnonKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY || publicAnonKey;

export const leadSubmitUrl =
  import.meta.env.VITE_LEAD_SUBMIT_URL ||
  `${supabaseUrl}/functions/v1/make-server-f3bc3770/submit-lead`;
